 
version: '1.0'
stages:
 - prepare
 - build
 - test
 - test2
 
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'codefreshdemo/cf-example-python-django'
    revision: master
    git: github
  build_my_image:
    title: Building Docker Image
    stage: build
    type: build
    image_name: my-django-image
    working_directory: ./
    tag: master
    dockerfile: Dockerfile
  test_my_image:
     title: Running unit tests
     stage: test
     image: '${{build_my_image}}'
     commands:
       - uname -a
       - ls -la 
       - pip install wget
       - wget -c https://wordpress.org/latest.tar.gz
  Freestyle:
  title: Running docker image
  type: freestyle
  working_directory: '${{CLONE_STEP_NAME}}'
  arguments:
    image: 'alpine:3.8'
    commands:
      - echo "Hello world"
      - echo "asdasd"

      
       
       
