version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sinesiobittencourt/shell_script"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls -la"
      - 
      - echo "============================================"
      - echo "A robot is now installing WordPress for you."
      - echo "============================================"
      - #download wordpress
      - curl -O https://wordpress.org/latest.tar.gz
      - #unzip wordpress
      - tar -zxvf latest.tar.gz
      - #change dir to wordpress
      - cd wordpress
      - #copy file to parent dir
      - cp -rf . ..
      - #move back to parent dir
      - cd ..
      - #remove files from wordpress folder
      - rm -R wordpress
      - #create wp config
      - cp wp-config-sample.php wp-config.php
    stage: "test"
 
